ubuntu:
  hosts:
    master1:
      ansible_host: localhost
      ansible_user: vagrant 
      ansible_port: 22222
      ansible_ssh_private_key_file: /home/micki/workspace/go/src/github.com/MickiFoerster/ansible/install-k8s/.vagrant/machines/testing-node-1/virtualbox/private_key
    worker1:
      ansible_host: localhost
      ansible_user: vagrant 
      ansible_port: 22223
      ansible_ssh_private_key_file: /home/micki/workspace/go/src/github.com/MickiFoerster/ansible/install-k8s/.vagrant/machines/testing-node-2/virtualbox/private_key
