ubuntu:
  hosts:
    k8s-single-node-11933:
      ansible_host: localhost
      ansible_user: vagrant 
      ansible_port: 2222
      ansible_ssh_private_key_file: /home/micki/MickiFoerster/ansible/install-k8s/.vagrant/machines/k8s-single-node-11933/virtualbox/private_key
