---
- hosts: ubuntu
  become: true
  become_user: root
  vars:
    memsize_kb: 2035000
    minimal_number_cpus: 2
  tasks:
    - name: Check size of memory
      ansible.builtin.script: helpers/mem.py {{memsize_kb}}
    - name: Check number of CPUs
      ansible.builtin.script: helpers/cpu.py {{minimal_number_cpus}}

- name: Enable Cgroup2
  ansible.builtin.import_playbook: ../enable-cgroup2/playbook.yaml

- name: Install CRI-O
  ansible.builtin.import_playbook: ../install-CRI-O/playbook.yaml

...
