---
- hosts: ubuntu
  become: true
  become_user: root
  vars:
    memsize_kb: 2035000
    minimal_number_cpus: 2
  vars_files:
    - vars.yaml
  tasks:
    - name: Check size of memory
      ansible.builtin.script: helpers/mem.py {{memsize_kb}}
    - name: Check number of CPUs
      ansible.builtin.script: helpers/cpu.py {{minimal_number_cpus}}
    - name: Disable swap for kubelet (see hints on kubernetes.io)
      ansible.builtin.script: helpers/turn-off-swap.sh
    - name: Fetch produc_uuid
      ansible.builtin.fetch:
        src: "{{path_product_uuid}}"
        dest: /tmp/product_uuid
    - name: Fetch machine ID 
      ansible.builtin.fetch:
        src: "{{path_machine_id}}"
        dest: /tmp/machine-id
    - name: Show interfaces
      ansible.builtin.debug:
        msg: "{{item}}"
      loop: "{{ ansible_interfaces }} "

- name: Check uniqness
  hosts: localhost
  connection: local
  vars_files:
      - vars.yaml
  tasks:
    - name: Show product UUIDs
      ansible.builtin.command: cat "/tmp/product_uuid/{{ item }}{{path_product_uuid}}"
      loop: "{{ groups['all'] }}"
    - name: Show machine IDs
      ansible.builtin.command: cat "/tmp/machine-id/{{ item }}{{path_machine_id}}"
      loop: "{{ groups['all'] }}"



        #- name: Enable Cgroup2
        #  ansible.builtin.import_playbook: ../enable-cgroup2/playbook.yaml
        #
        #- name: Install CRI-O
        #  ansible.builtin.import_playbook: ../install-CRI-O/playbook.yaml
        #
...
