# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
NUM_NODES = 2

IP_NW = "192.168.99."
IP_START = 100

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.box_check_update = false

  # Provision Master Nodes
  (1..NUM_NODES).each do |i|
    config.vm.define "testing-node-#{i}" do |testingnode|
      # Name shown in the GUI
      testingnode.vm.provider "virtualbox" do |vb|
        vb.name = "kubetestingnode#{i}"
        vb.memory = 2048
        vb.cpus = 2
      end
      testingnode.vm.hostname = "testingnode#{i}"
      testingnode.vm.network :private_network, ip: IP_NW + "#{IP_START + i}"
      testingnode.vm.network "forwarded_port", guest: 22, host: "#{22221 + i}"
    end
  end

end
