ubuntu:
  hosts:
    localhost:
      ansible_user: vagrant 
      ansible_port: 2222 
      ansible_ssh_private_key_file: /home/micki/workspace/go/src/github.com/MickiFoerster/ansible/install-kafka/.vagrant/machines/default/virtualbox/private_key
